layout_spectrum: 0.1548508
color:
  saturation: 0.9333476
  lightness: 0.1823694
  brandStrength: 0.7210821
  brandColors:
    - '#000000'
    - '#CECED0'
    - '#664B39'
    - '#7F6F65'
  rhythmicContrast: 0.3255597
typography_spectrum: 0.7112873
name: Santiagoc
